/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AddBooks {
        "adminName": string;
    }
    interface AdminHomepage {
    }
    interface AdminLogin {
    }
    interface AdminRegistration {
        "userName": string;
    }
    interface AllBooks {
        "adminName": string;
    }
    interface BookReturn {
    }
    interface BookSearch {
    }
    interface HomePage {
    }
    interface PlaceOrder {
    }
    interface ReturnRequest {
    }
    interface RootPage {
    }
    interface UserBookSearch {
    }
    interface UserHomepage {
    }
    interface UserLogin {
        "history": any;
        "userName": string;
    }
    interface UserRegistration {
        "userName": string;
    }
    interface ViewDateInfo {
    }
    interface ViewOrders {
    }
}
declare global {
    interface HTMLAddBooksElement extends Components.AddBooks, HTMLStencilElement {
    }
    var HTMLAddBooksElement: {
        prototype: HTMLAddBooksElement;
        new (): HTMLAddBooksElement;
    };
    interface HTMLAdminHomepageElement extends Components.AdminHomepage, HTMLStencilElement {
    }
    var HTMLAdminHomepageElement: {
        prototype: HTMLAdminHomepageElement;
        new (): HTMLAdminHomepageElement;
    };
    interface HTMLAdminLoginElement extends Components.AdminLogin, HTMLStencilElement {
    }
    var HTMLAdminLoginElement: {
        prototype: HTMLAdminLoginElement;
        new (): HTMLAdminLoginElement;
    };
    interface HTMLAdminRegistrationElement extends Components.AdminRegistration, HTMLStencilElement {
    }
    var HTMLAdminRegistrationElement: {
        prototype: HTMLAdminRegistrationElement;
        new (): HTMLAdminRegistrationElement;
    };
    interface HTMLAllBooksElement extends Components.AllBooks, HTMLStencilElement {
    }
    var HTMLAllBooksElement: {
        prototype: HTMLAllBooksElement;
        new (): HTMLAllBooksElement;
    };
    interface HTMLBookReturnElement extends Components.BookReturn, HTMLStencilElement {
    }
    var HTMLBookReturnElement: {
        prototype: HTMLBookReturnElement;
        new (): HTMLBookReturnElement;
    };
    interface HTMLBookSearchElement extends Components.BookSearch, HTMLStencilElement {
    }
    var HTMLBookSearchElement: {
        prototype: HTMLBookSearchElement;
        new (): HTMLBookSearchElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLPlaceOrderElement extends Components.PlaceOrder, HTMLStencilElement {
    }
    var HTMLPlaceOrderElement: {
        prototype: HTMLPlaceOrderElement;
        new (): HTMLPlaceOrderElement;
    };
    interface HTMLReturnRequestElement extends Components.ReturnRequest, HTMLStencilElement {
    }
    var HTMLReturnRequestElement: {
        prototype: HTMLReturnRequestElement;
        new (): HTMLReturnRequestElement;
    };
    interface HTMLRootPageElement extends Components.RootPage, HTMLStencilElement {
    }
    var HTMLRootPageElement: {
        prototype: HTMLRootPageElement;
        new (): HTMLRootPageElement;
    };
    interface HTMLUserBookSearchElement extends Components.UserBookSearch, HTMLStencilElement {
    }
    var HTMLUserBookSearchElement: {
        prototype: HTMLUserBookSearchElement;
        new (): HTMLUserBookSearchElement;
    };
    interface HTMLUserHomepageElement extends Components.UserHomepage, HTMLStencilElement {
    }
    var HTMLUserHomepageElement: {
        prototype: HTMLUserHomepageElement;
        new (): HTMLUserHomepageElement;
    };
    interface HTMLUserLoginElement extends Components.UserLogin, HTMLStencilElement {
    }
    var HTMLUserLoginElement: {
        prototype: HTMLUserLoginElement;
        new (): HTMLUserLoginElement;
    };
    interface HTMLUserRegistrationElement extends Components.UserRegistration, HTMLStencilElement {
    }
    var HTMLUserRegistrationElement: {
        prototype: HTMLUserRegistrationElement;
        new (): HTMLUserRegistrationElement;
    };
    interface HTMLViewDateInfoElement extends Components.ViewDateInfo, HTMLStencilElement {
    }
    var HTMLViewDateInfoElement: {
        prototype: HTMLViewDateInfoElement;
        new (): HTMLViewDateInfoElement;
    };
    interface HTMLViewOrdersElement extends Components.ViewOrders, HTMLStencilElement {
    }
    var HTMLViewOrdersElement: {
        prototype: HTMLViewOrdersElement;
        new (): HTMLViewOrdersElement;
    };
    interface HTMLElementTagNameMap {
        "add-books": HTMLAddBooksElement;
        "admin-homepage": HTMLAdminHomepageElement;
        "admin-login": HTMLAdminLoginElement;
        "admin-registration": HTMLAdminRegistrationElement;
        "all-books": HTMLAllBooksElement;
        "book-return": HTMLBookReturnElement;
        "book-search": HTMLBookSearchElement;
        "home-page": HTMLHomePageElement;
        "place-order": HTMLPlaceOrderElement;
        "return-request": HTMLReturnRequestElement;
        "root-page": HTMLRootPageElement;
        "user-book-search": HTMLUserBookSearchElement;
        "user-homepage": HTMLUserHomepageElement;
        "user-login": HTMLUserLoginElement;
        "user-registration": HTMLUserRegistrationElement;
        "view-date-info": HTMLViewDateInfoElement;
        "view-orders": HTMLViewOrdersElement;
    }
}
declare namespace LocalJSX {
    interface AddBooks {
        "adminName"?: string;
    }
    interface AdminHomepage {
    }
    interface AdminLogin {
    }
    interface AdminRegistration {
        "userName"?: string;
    }
    interface AllBooks {
        "adminName"?: string;
    }
    interface BookReturn {
    }
    interface BookSearch {
    }
    interface HomePage {
    }
    interface PlaceOrder {
    }
    interface ReturnRequest {
    }
    interface RootPage {
    }
    interface UserBookSearch {
    }
    interface UserHomepage {
    }
    interface UserLogin {
        "history"?: any;
        "userName"?: string;
    }
    interface UserRegistration {
        "userName"?: string;
    }
    interface ViewDateInfo {
    }
    interface ViewOrders {
    }
    interface IntrinsicElements {
        "add-books": AddBooks;
        "admin-homepage": AdminHomepage;
        "admin-login": AdminLogin;
        "admin-registration": AdminRegistration;
        "all-books": AllBooks;
        "book-return": BookReturn;
        "book-search": BookSearch;
        "home-page": HomePage;
        "place-order": PlaceOrder;
        "return-request": ReturnRequest;
        "root-page": RootPage;
        "user-book-search": UserBookSearch;
        "user-homepage": UserHomepage;
        "user-login": UserLogin;
        "user-registration": UserRegistration;
        "view-date-info": ViewDateInfo;
        "view-orders": ViewOrders;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "add-books": LocalJSX.AddBooks & JSXBase.HTMLAttributes<HTMLAddBooksElement>;
            "admin-homepage": LocalJSX.AdminHomepage & JSXBase.HTMLAttributes<HTMLAdminHomepageElement>;
            "admin-login": LocalJSX.AdminLogin & JSXBase.HTMLAttributes<HTMLAdminLoginElement>;
            "admin-registration": LocalJSX.AdminRegistration & JSXBase.HTMLAttributes<HTMLAdminRegistrationElement>;
            "all-books": LocalJSX.AllBooks & JSXBase.HTMLAttributes<HTMLAllBooksElement>;
            "book-return": LocalJSX.BookReturn & JSXBase.HTMLAttributes<HTMLBookReturnElement>;
            "book-search": LocalJSX.BookSearch & JSXBase.HTMLAttributes<HTMLBookSearchElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "place-order": LocalJSX.PlaceOrder & JSXBase.HTMLAttributes<HTMLPlaceOrderElement>;
            "return-request": LocalJSX.ReturnRequest & JSXBase.HTMLAttributes<HTMLReturnRequestElement>;
            "root-page": LocalJSX.RootPage & JSXBase.HTMLAttributes<HTMLRootPageElement>;
            "user-book-search": LocalJSX.UserBookSearch & JSXBase.HTMLAttributes<HTMLUserBookSearchElement>;
            "user-homepage": LocalJSX.UserHomepage & JSXBase.HTMLAttributes<HTMLUserHomepageElement>;
            "user-login": LocalJSX.UserLogin & JSXBase.HTMLAttributes<HTMLUserLoginElement>;
            "user-registration": LocalJSX.UserRegistration & JSXBase.HTMLAttributes<HTMLUserRegistrationElement>;
            "view-date-info": LocalJSX.ViewDateInfo & JSXBase.HTMLAttributes<HTMLViewDateInfoElement>;
            "view-orders": LocalJSX.ViewOrders & JSXBase.HTMLAttributes<HTMLViewOrdersElement>;
        }
    }
}
